theme: jekyll-theme-cayman

title: "UTIL: An Ultra-wideband Time-difference-of-arrival Indoor Localization Dataset"
description: 
show_downloads: true

github:
  script_zip_url: https://github.com/utiasDSL/util-uwb-dataset/archive/refs/tags/Dataset-v1.0.zip
  data_zip_url: https://github.com/utiasDSL/util-uwb-dataset/releases/download/Dataset-v1.0/dataset.7z


