theme: jekyll-theme-cayman

title: Ultra-wideband dataset for indoor localization
description: Ultra-wideband dataset for indoor localization
show_downloads: true

github:
  zip_url: https://github.com/utiasDSL/utias_uwb_dataset/archive/master.zip
  tar_url: https://github.com/utiasDSL/utias_uwb_dataset/tarball/master 

logo: /files/readme_images/helix.png
